version: "3.4"
services:
  neko:
    image: "ghcr.io/m1k1o/neko/firefox:latest"
    restart: "unless-stopped"
    shm_size: "2gb"
    ports:
      - "8080:8080"
      - "52000-52100:52000-52100/udp"
    environment:
      NEKO_SCREEN: "1920x1080@30"
      NEKO_PASSWORD: "admin"
      NEKO_PASSWORD_ADMIN: "admin"
      NEKO_EPR: "52000-52100"
      NEKO_NAT1TO1: "127.0.0.1"
      NEKO_ICELITE: 1
      NEKO_IMPLICIT_CONTROL: "true"
    volumes:
      - neko_data:/home/neko/.mozilla/firefox
    cap_add:
      - SYS_ADMIN

volumes:
  neko_data:
